"""Install a generated widget into a KiCad library and register it for placement.

The Phase 13 plugin writes the *byte-identical* footprint/symbol the standalone
tool emits into a KiCad **library** — a ``.pretty`` directory of ``.kicad_mod``
files plus a shared ``.kicad_sym`` file — and registers that library in a library
table so KiCad's *Add Footprint* / *Add Symbol* pickers find it.

The destination is configurable (see :class:`LibraryTarget`):

* **project scope** (default) — a ``captouch`` library inside the open project's
  own directory, referenced via ``${KIPRJMOD}`` and registered in the project's
  ``fp-lib-table`` / ``sym-lib-table``;
* **global scope** — a personal library shared across every project, registered in
  KiCad's global tables with an absolute path.

The footprint ``.pretty`` and the symbol ``.kicad_sym`` are *independent* paths, so
they may live in two different directories (e.g. footprints in a shared mechanical
library, symbols in the project). Everything here is pure file I/O over the shared
:mod:`captouch.engine` output and the :mod:`captouch.sexpr` reader/writer — no
KiCad, kipy, or Qt imports — so it is fully testable headlessly.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path

from .. import engine
from ..export import symbol
from ..params import WidgetParams
from ..sexpr import Sym, children, dumps, find, find_all, head, loads

__all__ = [
    "DEFAULT_NICKNAME",
    "LibraryError",
    "LibraryTarget",
    "InstallResult",
    "project_target",
    "make_target",
    "kicad_config_dir",
    "install",
    "install_widget",
]

DEFAULT_NICKNAME = "captouch"
DEFAULT_DESCR = "Capacitive-touch widgets generated by kicad-captouch"
# Library-table format version written by KiCad 7–10 for both fp- and sym-lib-tables.
LIB_TABLE_VERSION = 7
# KiCad's per-project path variable; expands to the project directory at load time.
KIPRJMOD = "${KIPRJMOD}"


class LibraryError(ValueError):
    """Raised when a library destination cannot be resolved or written."""


@dataclass(frozen=True)
class LibraryTarget:
    """Where a widget's footprint and symbol are written and registered.

    The footprint and symbol carry independent destinations and table entries, so a
    caller can split them across libraries. Build one with :func:`project_target`
    (project-local, the default) or :func:`make_target` (arbitrary location/scope).
    """

    nickname: str
    fp_dir: Path  # the ``.pretty`` directory that holds the ``.kicad_mod``
    sym_path: Path  # the shared ``.kicad_sym`` file
    fp_table: Path  # ``fp-lib-table`` the footprint library is registered in
    sym_table: Path  # ``sym-lib-table`` the symbol library is registered in
    fp_uri: str  # URI string stored in ``fp-lib-table`` (may use ``${KIPRJMOD}``)
    sym_uri: str  # URI string stored in ``sym-lib-table``
    descr: str = DEFAULT_DESCR


@dataclass(frozen=True)
class InstallResult:
    """What :func:`install` wrote — enough to tell the user how to place the part."""

    name: str  # the widget name, e.g. ``CT_Slider``
    nickname: str  # the library nickname, e.g. ``captouch``
    fp_id: str  # ``nickname:name`` — the id typed into Add Footprint
    fp_path: Path
    sym_path: Path
    fp_table: Path
    sym_table: Path
    fp_registered: bool  # True if the fp-lib-table entry was added or updated
    sym_registered: bool  # True if the sym-lib-table entry was added or updated


# --------------------------------------------------------------------------- #
# Target construction
# --------------------------------------------------------------------------- #
def _uri(path: Path, project_dir: Path | None) -> str:
    """``${KIPRJMOD}``-relative URI when *path* is under *project_dir*, else absolute.

    KiCad expands ``${KIPRJMOD}`` to the project directory, so a project-local
    library stays portable when the project moves; anything outside the project is
    stored as an absolute path.
    """
    path = path.resolve()
    if project_dir is not None:
        project_dir = project_dir.resolve()
        try:
            rel = path.relative_to(project_dir)
        except ValueError:
            pass
        else:
            return f"{KIPRJMOD}/{rel.as_posix()}"
    return str(path)


def project_target(project_dir: Path | str, nickname: str = DEFAULT_NICKNAME) -> LibraryTarget:
    """A project-local ``nickname`` library registered in the project's tables."""
    return make_target(
        nickname=nickname,
        fp_dir=Path(project_dir) / f"{nickname}.pretty",
        sym_path=Path(project_dir) / f"{nickname}.kicad_sym",
        project_dir=Path(project_dir),
        scope="project",
    )


def make_target(
    *,
    nickname: str,
    fp_dir: Path | str,
    sym_path: Path | str,
    scope: str = "project",
    project_dir: Path | str | None = None,
    global_dir: Path | str | None = None,
    descr: str = DEFAULT_DESCR,
) -> LibraryTarget:
    """Build a :class:`LibraryTarget` for an arbitrary footprint/symbol location.

    *scope* ``"project"`` registers in ``<project_dir>/{fp,sym}-lib-table`` (and
    uses ``${KIPRJMOD}`` URIs for paths under the project); ``"global"`` registers
    in KiCad's global tables (``global_dir`` or :func:`kicad_config_dir`) with
    absolute URIs. *fp_dir* and *sym_path* may point anywhere — they need not share
    a directory.
    """
    fp_dir = Path(fp_dir)
    sym_path = Path(sym_path)
    if scope == "global":
        gdir = Path(global_dir) if global_dir is not None else kicad_config_dir()
        if gdir is None:
            raise LibraryError(
                "could not locate KiCad's global library tables; pass global_dir "
                "or use project scope"
            )
        fp_table, sym_table = gdir / "fp-lib-table", gdir / "sym-lib-table"
        proj = None  # global entries always use absolute URIs
    elif scope == "project":
        if project_dir is None:
            raise LibraryError("project scope needs a project_dir")
        proj = Path(project_dir)
        fp_table, sym_table = proj / "fp-lib-table", proj / "sym-lib-table"
    else:
        raise LibraryError(f"unknown scope {scope!r} (expected 'project' or 'global')")

    return LibraryTarget(
        nickname=nickname,
        fp_dir=fp_dir,
        sym_path=sym_path,
        fp_table=fp_table,
        sym_table=sym_table,
        fp_uri=_uri(fp_dir, proj),
        sym_uri=_uri(sym_path, proj),
        descr=descr,
    )


def kicad_config_dir() -> Path | None:
    """Best-effort path to KiCad's user config dir holding the global lib tables.

    Returns the newest versioned subdirectory (e.g. ``.../kicad/10.0``) that exists,
    or the base dir if it has the tables directly, or ``None`` if nothing is found.
    Platform-specific and overridable (callers may pass ``global_dir`` instead).
    """
    if sys.platform == "darwin":
        base = Path.home() / "Library" / "Preferences" / "kicad"
    elif sys.platform.startswith("win"):
        import os

        appdata = os.environ.get("APPDATA")
        base = Path(appdata) / "kicad" if appdata else Path.home() / "AppData" / "Roaming" / "kicad"
    else:
        base = Path.home() / ".config" / "kicad"

    if not base.is_dir():
        return None
    versions = sorted(
        (d for d in base.iterdir() if d.is_dir() and (d / "fp-lib-table").exists()),
        key=lambda d: d.name,
    )
    if versions:
        return versions[-1]
    return base if (base / "fp-lib-table").exists() else None


# --------------------------------------------------------------------------- #
# Installation
# --------------------------------------------------------------------------- #
def install_widget(
    params: WidgetParams,
    target: LibraryTarget | None = None,
    *,
    project_dir: Path | str | None = None,
) -> InstallResult:
    """Build *params*'s geometry and :func:`install` it (CLI/headless convenience).

    Pass an explicit *target*, or *project_dir* to default to a project-local
    ``captouch`` library.
    """
    return install(engine.build_widget(params), target, project_dir=project_dir)


def install(
    geo: engine.WidgetGeometry,
    target: LibraryTarget | None = None,
    *,
    project_dir: Path | str | None = None,
) -> InstallResult:
    """Write *geo*'s footprint + symbol into *target* and register both libraries.

    With no *target*, *project_dir* is required and a project-local ``captouch``
    library is used. The footprint is byte-identical to the standalone output; the
    symbol is merged into the (possibly shared) ``.kicad_sym``, replacing any
    same-named part. Registration is idempotent.
    """
    if target is None:
        if project_dir is None:
            raise LibraryError("install needs either a target or a project_dir")
        target = project_target(project_dir)

    name = geo.params.name
    fp_text, _ = engine.export_widget(geo)

    fp_path = target.fp_dir / f"{name}.kicad_mod"
    target.fp_dir.mkdir(parents=True, exist_ok=True)
    fp_path.write_text(fp_text, encoding="utf-8")

    existing = target.sym_path.read_text(encoding="utf-8") if target.sym_path.exists() else None
    merged = symbol.merge_symbol_into_lib(symbol.widget_symbol(geo), existing)
    target.sym_path.parent.mkdir(parents=True, exist_ok=True)
    target.sym_path.write_text(merged, encoding="utf-8")

    fp_registered = _register(
        target.fp_table, "fp_lib_table", target.nickname, target.fp_uri, target.descr
    )
    sym_registered = _register(
        target.sym_table, "sym_lib_table", target.nickname, target.sym_uri, target.descr
    )

    return InstallResult(
        name=name,
        nickname=target.nickname,
        fp_id=f"{target.nickname}:{name}",
        fp_path=fp_path,
        sym_path=target.sym_path,
        fp_table=target.fp_table,
        sym_table=target.sym_table,
        fp_registered=fp_registered,
        sym_registered=sym_registered,
    )


# --------------------------------------------------------------------------- #
# Library-table registration (fp-lib-table / sym-lib-table)
# --------------------------------------------------------------------------- #
def _lib_entry(nickname: str, uri: str, descr: str) -> list:
    """One ``(lib (name …)(type "KiCad")(uri …)(options "")(descr …))`` node."""
    return [
        Sym("lib"),
        [Sym("name"), nickname],
        [Sym("type"), "KiCad"],
        [Sym("uri"), uri],
        [Sym("options"), ""],
        [Sym("descr"), descr],
    ]


def _entry_name(entry: list) -> str | None:
    node = find(entry, "name")
    return node[1] if node is not None and len(node) > 1 else None


def _entry_uri(entry: list) -> str | None:
    node = find(entry, "uri")
    return node[1] if node is not None and len(node) > 1 else None


def _register(table_path: Path, root: str, nickname: str, uri: str, descr: str) -> bool:
    """Ensure *table_path* has a ``KiCad`` lib entry named *nickname* pointing at *uri*.

    Creates the table if absent, leaves any other entries untouched, and is
    idempotent: returns ``False`` (no write) when the entry already matches, ``True``
    when it adds a new entry or rewrites a stale URI. Whitespace in a pre-existing
    table is normalised on rewrite — semantically identical, and KiCad reformats it
    on its next save anyway.
    """
    if table_path.exists():
        table = loads(table_path.read_text(encoding="utf-8"))
        if not isinstance(table, list) or head(table) != root:
            raise LibraryError(f"{table_path} is not a {root}")
    else:
        table = [Sym(root), [Sym("version"), LIB_TABLE_VERSION]]

    existing = next(
        (e for e in find_all(table, "lib") if _entry_name(e) == nickname),
        None,
    )
    if existing is not None:
        if _entry_uri(existing) == uri:
            return False  # already registered at this URI — nothing to do
        table = [
            c if c is not existing else _lib_entry(nickname, uri, descr) for c in children(table)
        ]
        table = [Sym(root), *table]
    else:
        table = [*table, _lib_entry(nickname, uri, descr)]

    table_path.parent.mkdir(parents=True, exist_ok=True)
    table_path.write_text(dumps(table) + "\n", encoding="utf-8")
    return True
